### ISSUE TITLE
Implement skeleton of services infrastructure

### ISSUE THREAD

**Issue by iprunache** [cami-project/cami-project#5]
## Why

Test setups of the technologies that will represent the core of the CAMI service infrastructure.

The infrastructure needs to be easy to provision and the technologies used should be able to provide the functionalities needed by the 4 scenarios that currently have a breakdown(H2, S4, H4.1, H4.2).
## What
- [x] #6 setup MySQL instance that will act as data store
- [x] #7 setup Python API reading data from MySQL through Django ORM
- [x] #8 implement a Python daemon that will be used as the core of a CAMI service
- [x] #9 setup RabbitMQ for message passing between services
- [x] #11 use Docker to run each of the daemons and APIs in a container
- [ ] #10 write mock scenario that involves 2 daemons communicating through message queues and using the data store API

**Comment by rtud** [comment]
@iprunache: issue #10 has been deprecated and I've marked the rest as completed since they all have been merged. Closing, thank you!
